project-1/my_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :workers

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'ping' => 'sessions#ping' # for ELB health check

  root 'sessions#new'

  post '/ece1779/servlet/FileUpload' => 'images#create'

  resources :users, :except => [:show, :destroy] do 
    resources :images do
      resources :thumbnails, :only => [:show]
    end
  end

  namespace :manager do
    get '/' => 'workers#index'
    resources :workers, :only => [:index, :show] do
      delete :terminate_worker
    end
    post   :start_elb # singleton
    put    :start_worker
    post   :purge_images
    post   :reset_alarms

    get    :worker_status
    get    :elb_status
    get    :image_stats

    post   :auto_scale
    post   :aws_alarm

    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

end

project-1/my_app/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MyApp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") MyApp
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            - if current_user
              %li= link_to "My Images", user_images_path(current_user)
            %li= link_to "Manager", manager_login_path
            - if logged_in?
              %li= link_to "Log out (#{current_user.login})", logout_path, method: "delete"
            - else
              %li= link_to "Log in", login_path
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          / .well.sidebar-nav
          /   %h3 Sidebar
          /   %ul.nav.nav-list
          /     %li.nav-header Sidebar
          /     %li= link_to "Link 1", "/path1"
          /     %li= link_to "Link 2", "/path2"
          /     %li= link_to "Link 3", "/path3"
      %footer
        / %p &copy; Company 2015

project-1/my_app/app/views/layouts/manager.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MyApp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") MyApp
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            / %li= link_to "Users", "/users"
            - if current_user
              %li= link_to "My Images", user_images_path(current_user)
            %li= link_to "Manager", manager_login_path
            - if logged_in?
              %li= link_to "Log out (#{current_user.login})", logout_path, method: "delete"
            - else
              %li= link_to "Log in", login_path
            - if manager_logged_in?
              %li= link_to "Log out (manager)", manager_logout_path, method: "delete"
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3 Handy Links
            %ul.nav.nav-list
              / %li.nav-header Sidebar
              %li= link_to "AWS Console", "https://console.aws.amazon.com/ec2/v2/home?region=us-east-1", :target => "_blank"
      %footer
        / %p &copy; Company 2015