project-1/my_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :workers

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'ping' => 'sessions#ping' # for ELB health check

  root 'sessions#new'

  post '/ece1779/servlet/FileUpload' => 'images#create'

  resources :users, :except => [:show, :destroy] do 
    resources :images do
      resources :thumbnails, :only => [:show]
    end
  end

  namespace :manager do
    get '/' => 'workers#index'
    resources :workers, :only => [:index, :show] do
      delete :terminate_worker
    end
    post   :start_elb # singleton
    put    :start_worker
    post   :purge_images
    post   :reset_alarms

    get    :worker_status
    get    :elb_status
    get    :image_stats

    post   :auto_scale
    post   :aws_alarm

    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

end

project-1/my_app/app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :user, foreign_key: "userId"

  validates :user, presence: true

  validates :uuid, presence: true, uniqueness: true # , allow_nil: true

  # Removed in favour of synchronous image upload in the controller
  # after_commit   :dispatch_upload_job, on: :create
  
  after_save     :check_and_delete_tmpfile_after_transformations
  before_destroy :delete_assets
  before_destroy :delete_tempfile

  cattr_reader   :uuid_generator

  ### Accessors

  # Save the upload to a file that the various upload/transform jobs use
  def file=(value)
    if value == nil
      delete_tempfile
    else
      tempfile = File.new(tempfile_path, "wb+")
      tempfile.write(value.read)
      tempfile.close
    end
  end

  def uuid
    unless u = read_attribute(:uuid)
      self.uuid = u = Image.uuid_generator.generate
    end
    u
  end

  ### Helpers

  def s3_base_key
    File.join("images", user.id.to_s, self.id.to_s)
  end

  def s3_key(filename)
    File.join(s3_base_key, filename)
  end

  def s3_key_for_thumb(key)
    s3_key("#{key.to_s}#{extension}")
  end

  def s3_key_for_original
    s3_key("original#{extension}")
  end

  def s3_key_for_key(key)
    (key == :key1 ? s3_key_for_original : s3_key_for_thumb(key))
  end

  def self.s3_bucket_name
    YAML.load(File.read('config/aws.yml'))[Rails.env.to_s]["bucket"]
  end

  def self.s3_bucket
    @bucket ||= AWS::S3.new.buckets[Image.s3_bucket_name]
  end

  def self.s3_object_for_key(key)
    Image.s3_bucket.objects[key] 
  end

  def tempfile_path
    uuid.present? ? File.join(Dir.tmpdir, uuid) : nil
  end

  def key_uploaded?(key)
    # Convention: key is a non-nil value then it's been uploaded
    self.send(key).present?

    # extra check: does it actually exists in S3?
    # s3_key = s3_key_for_key(key)
    # s3_object = Image.s3_object_for_key(s3_key)
    # s3_object.exists?
  end

  def self.transform_params_for_key(key)
    case key.to_s
    when "key2"
      [100,100]
    when "key3"
      [200,200]
    when "key4"
      [300,300]
    else
      raise "Unsupported key: #{key}"
    end
  end

  def dispatch_image_transformations!
    Rails.logger.info "[Image] Dispatching TransformImageWorker jobs"
    self.key2.nil? && TransformImageWorker.perform_async(id, :key2)
    self.key3.nil? && TransformImageWorker.perform_async(id, :key3)
    self.key4.nil? && TransformImageWorker.perform_async(id, :key4)
  end

  private

  def image_keys
    [:key1, :key2, :key3, :key4]
  end

  def original_uploaded_to_s3?
    self.key1.present?
  end

  def dispatch_upload_job
    Rails.logger.info "[Image] Dispatching UploadImageOriginalWorker job"
    UploadImageOriginalWorker.perform_async(self.id)
    true
  end

  def delete_assets
    Rails.logger.debug "Deleting Image #{id} assets"
    image_keys.each do |k|
      v = self.send(k) && DeleteImageWorker.perform_async(v)
    end
    true
  end

  def delete_tempfile
    Rails.logger.debug "KEYS: " + image_keys.map{|k| send(k)}.join(", ")
    Rails.logger.debug "Deleting tempfile? #{tempfile_path} for Image #{id}"
    unless !File.exists?(tempfile_path)
      Rails.logger.info "Deleting Image #{id} tempfile: #{tempfile_path}"
      File.unlink(tempfile_path)
    end
  end

  def check_and_delete_tmpfile_after_transformations
    if image_keys.all?{|k| send(k).present?}
      delete_tempfile
    end
    true
  end

  def self.uuid_generator
    @@uuid_generator ||= UUID.new
  end

end

project-1/my_app/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  ImagesController::BUCKET = "ece1779"

  # Assumption: the load-testing utility doesn't login or maintain a session
  skip_before_action :authenticate, only: :create

  before_action :set_image, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :create 

  def index
    @images = current_user.images
  end

  def new
    @image = Image.new
  end

  def show
    # Thumbnails handled by ThumbnailsController

    # Get the URL for the original (assumed to be on S3 by this point)
    # TODO: merge this with the logic in ThumbnailsController
    url_expiry = 10.minutes.to_i
    object = Image.s3_object_for_key(@image.key1)
    url = object.url_for(:read, :expires => url_expiry)
    @original_url = url.to_s
  end

  def create
    # We get two kinds of POSTs here:
    # 1) regular users (who have logged in) and are POSTing with the standard form on the browser
    # 2) the load-testing utility (assumption: which doesn't login)
    #
    # For #1, we follow the regular Rails conventions (params[:image] contains the POST data)
    # For #2, we assume that the POST data is at the top level of params
    #
    # Test #2 with:
    #   curl --form "uploadedfile=@my-file.txt;filename=desired-filename.txt" --form userID=1 --form param2=value2 http://127.0.0.1:3000/ece1779/servlet/FileUpload
    #
    # In both cases, we expect params[:userID] to be present.
    
    if request.path == "/ece1779/servlet/FileUpload"
      @current_user = User.find_or_create_by(id: params[:userID]) do |user|
        user.login = "user" + params[:userID]
        user.password = "password" + params[:userID]
      end
    else
      @current_user = User.find params[:userID]  
    end

    safe_params = params[:image].present? ? image_params(params[:image]) : image_params(params)

    @image = Image.new(safe_params)
    respond_to do |format|
      if @image.save 

        # Force syncronous upload
        UploadImageOriginalWorker.new.perform(@image.id)

        format.html { redirect_to user_images_path(@current_user), notice: 'Image was successfully uploaded.' }
        format.json { render :show, status: :created, location: @image }
      else
        @image.file = nil # cleanup
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::RecordNotFound => e
    # no current_user found
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'You do not have an account.', status: :unauthorized }
      format.json { head :unauthorized }
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to user_images_path(current_user), notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = current_user.images.find params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # Note that the load-tester posts to non-nested params
  def image_params(params)
    # From the requirements:
    #
    # field1 name = userID type = string
    # field2 name = uploadedfile type = file

    file = params[:uploadedfile]
    original_filename = file.original_filename
    extension = File.extname(original_filename)

    {user: @current_user, file: file, original_filename: original_filename, extension: extension}
  end

end

project-1/my_app/app/helpers/images_helper.rb
module ImagesHelper
  def thumbnail_preview_url_for_image(i)
    user_image_thumbnail_path(current_user, i, "key2")
  end
end

project-1/my_app/app/views/images/_form.html.haml
= form_for @image, :url => user_images_path(@current_user), :html => {class: "form-signin"} do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg
  %h3.form-signin-heading Upload An Image
  %p.help-block Select an image to upload
  .form_group
    = hidden_field_tag 'userID', params[:user_id]
    = f.file_field :uploadedfile
  %br
  
  .form_group
    = f.button 'Save', class: "btn btn-primary"
  

project-1/my_app/app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

project-1/my_app/app/views/images/index.html.haml
%h1 My Images

%br
= link_to(new_user_image_path(current_user), class: "btn btn-primary") do
  %span.glyphicon.glyphicon-upload 
  Upload an Image

- if @images.any?
  .container-fluid
    .row
      %table.table.table-striped
        %thead
          %tr
            %th ID
            %th File name
            %th Preview
            %th Actions
        %tbody
          - @images.each do |image|
            %tr
              %td.text-muted
                = link_to image.id, user_image_path(current_user, image)
              %td
                = link_to image.original_filename, user_image_path(current_user, image)
              %td= link_to image_tag(thumbnail_preview_url_for_image(image)), user_image_path(current_user, image)
              / %td= link_to 'Edit',    edit_user_image_path(current_user, image)
              %td= link_to 'Delete', user_image_path(current_user, image), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

project-1/my_app/app/views/images/new.html.haml
= provide(:title, "Upload image")

= render 'form'

%br
%br
= link_to 'Back to Images', user_images_path(current_user), class: "btn btn-info"
%br
%br

project-1/my_app/app/views/images/show.html.haml
%p#notice= notice

%h3= "#{@image.original_filename} (ID: #{@image.id})"

.thumbnail
  =link_to "#" do 
    =image_tag(@original_url, alt: "Original")
  .caption
    %h3 Original
.thumbnail
  =link_to "#" do 
    = image_tag(user_image_thumbnail_path(current_user, @image, "key2"), alt: "First")
    / =image_tag(@key2_url, alt: "First")
  .caption
    %h3 First Transformation - Resized to 100x100
.thumbnail
  =link_to "#" do 
    = image_tag(user_image_thumbnail_path(current_user, @image, "key3"), alt: "Second")
  .caption
    %h3 Second Transformation - Resized to 200x200
.thumbnail
  =link_to "#" do 
    = image_tag(user_image_thumbnail_path(current_user, @image, "key4"), alt: "Third")
  .caption
    %h3 Third Transformation - Resized to 300x300

= link_to 'Back to Images', user_images_path(current_user), class: "btn btn-info"
%br
%br