project-1/my_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :workers

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'ping' => 'sessions#ping' # for ELB health check

  root 'sessions#new'

  post '/ece1779/servlet/FileUpload' => 'images#create'

  resources :users, :except => [:show, :destroy] do 
    resources :images do
      resources :thumbnails, :only => [:show]
    end
  end

  namespace :manager do
    get '/' => 'workers#index'
    resources :workers, :only => [:index, :show] do
      delete :terminate_worker
    end
    post   :start_elb # singleton
    put    :start_worker
    post   :purge_images
    post   :reset_alarms

    get    :worker_status
    get    :elb_status
    get    :image_stats

    post   :auto_scale
    post   :aws_alarm

    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

end

project-1/my_app/app/controllers/manager/workers_controller.rb
class Manager::WorkersController < ManagerController
  skip_before_filter :authenticate

  def index
    @autoscale = AutoScale.instance
  end

  def terminate_worker
    instance_id = params[:worker_id]
    worker = Worker.with_id(instance_id)
    raise "Worker cannot be terminated" unless worker.can_terminate?
    TerminateWorker.perform_in(5.seconds, instance_id) # in case we're terminating ourselves
    elb.deregister_worker(worker)
    redirect_to manager_workers_path
  end
end

project-1/my_app/app/controllers/manager_controller.rb
require 'httparty'

class ManagerController < ApplicationController
  include AwsBoilerplate

  skip_before_filter    :authenticate
  before_action         :authenticate_manager, :except => [:new, :create, :aws_alarm]
  protect_from_forgery  :except => :aws_alarm
  
  def new
    redirect_to manager_path if manager_logged_in?
  end

  def create 
    if is_manager?(params["login"], params["password"])
      log_in_manager
      redirect_to manager_path
    else
      # Create an error message.
      flash.now[:danger] = 'Incorrect login/password combination'
      render 'new'
    end
  end

  def destroy
    log_out_manager if manager_logged_in?        
    redirect_to manager_login_path
  end

  def start_worker
    disable_api_termination = false
    worker = Worker.launch_worker(true, disable_api_termination)
    Elb.instance.register_worker(worker)
    redirect_to manager_workers_path
  end

  def start_elb
    Elb.create_load_balancer(self.class.my_availability_zone)
    add_all_running_instances_to_elb!
    redirect_to manager_workers_path
  end

  def reset_alarms
    Elb.instance.reset_alarm_subscriptions!
  end

  def purge_images
    Image.delete_all

    # Image.s3_bucket.clear! # This takes forever and can timeout the web request
    ClearS3BucketWorker.perform_async

    redirect_to manager_workers_path
  end

  def image_stats
    @elb = elb
    @workers = @elb.workers # Worker.all
    @health = @elb.health
    render :layout => false
  end

  def elb_status
    @elb = elb
    render :layout => false
  end

  def worker_status
    @elb = elb
    @workers = @elb.workers # Worker.all
    @health = @elb.health
    render :layout => false
  end

  def auto_scale
    autoscale = AutoScale.instance
    autoscale.update_attributes(autoscale_params)
    if !autoscale.save
      respond_to do |format|
        # FIXME: move this into a partial
        format.js { render :js => "alert('Validation Error: #{autoscale.errors.full_messages.to_sentence}'); $('#form-autoscale .spinner').hide();", :status => 400 }
      end
    else
      update_cw_alarms
      respond_to do |format|
        format.js  { render :layout => false }
      end
    end
  end

  # TODO: this could use some security since anything can POST to it...
  def aws_alarm
    # taken from: http://tech.xogroupinc.com/post/79166302844/creating-sns-subscription-endpoints-with-ruby-on
    
    # get amazon message type and topic
    amz_message_type = request.headers['x-amz-sns-message-type']
    amz_sns_topic = request.headers['x-amz-sns-topic-arn']

    # return unless !amz_sns_topic.nil? &&
    #   amz_sns_topic.to_s.downcase ==  'arn:aws:sns:us-east-1:460932295327:cpu_threshold'

    return unless amz_sns_topic.present?
    Rails.logger.info "[AWS ALARM] Received for topic #{amz_sns_topic} (type: #{amz_message_type})"

    request_body = JSON.parse request.body.read
    Rails.logger.info "[AWS ALARM] Request headers: #{request.headers}"
    Rails.logger.info "[AWS ALARM] Request body: #{request_body}"

    # if this is the first time confirmation of subscription, then confirm it
    if amz_message_type.to_s.downcase == 'subscriptionconfirmation'
      send_subscription_confirmation request_body
      Rails.logger.info "[AWS ALARM] CONFIRMING SUBSCRIPTION."
      head status: :accepted and return
    end

    if amz_message_type.to_s.downcase == 'notification'
      # Includes debugging mechanisms
      if request_body["Subject"] == "grow"
        target_size = request_body["Message"].to_i
        Rails.logger.info "[AWS ALARM] TEST GROW TO #{target_size}"
        self.class.grow_cluster(target_size)
      elsif request_body["Subject"] == "shrink"
        target_size = request_body["Message"].to_i
        Rails.logger.info "[AWS ALARM] TEST SHRINK TO #{target_size}"
        self.class.shrink_cluster(target_size)
      elsif AutoScale.instance.enabled?
        Rails.logger.info "[AWS ALARM] Calling rebalance_cluster_if_necessary"
        self.class.rebalance_cluster_if_necessary 
      else
        Rails.logger.info "[AWS ALARM] NO ACTION."
      end
    end
    head status: :accepted
  end

  private

  def add_all_running_instances_to_elb!
    instances = self.class.all_running_instances.select{|i| i.status == :running}
    elb = Elb.instance

    instances.each do |i|
      Rails.logger.info "Adding Instance #{i.id} to ELB"
      w = Worker.new(i)
      elb.register_worker(w)
    end
  end

  def update_cw_alarms
    autoscale = AutoScale.instance
    cw ||= Cloudwatch.instance
    # if autoscale.enabled?
      cw.update_all_high_cpu_alarms(elb.workers, autoscale.grow_cpu_thresh) 
      cw.update_all_low_cpu_alarms(elb.workers, autoscale.shrink_cpu_thresh) 
    # else 
    #   cw.update_all_high_cpu_alarms(elb.workers, 100.0)
    #   cw.update_all_low_cpu_alarms(elb.workers, 0.0)
    # end
  end

  def elb
    @elb ||= Elb.instance
  end

  def send_subscription_confirmation(request_body)
    subscribe_url = request_body['SubscribeURL']
    return nil unless !subscribe_url.to_s.empty? && !subscribe_url.nil?
    subscribe_confirm = HTTParty.get subscribe_url
  end

  ###
  # TODO: move this into a service

  def autoscale_params
    params.require(:auto_scale).permit(:grow_cpu_thresh, :shrink_cpu_thresh, :grow_ratio_thresh, :shrink_ratio_thresh, :enabled, :max_instances, :cooldown_period_in_seconds)
  end

end

project-1/my_app/app/helpers/manager/workers_helper.rb
module Manager::WorkersHelper
  def worker_health(worker)
    @health[worker.instance.id][:state] rescue "-"
  end

  def worker_public_ip(worker)
    if worker.instance.public_ip_address
      link_to worker.instance.public_ip_address, "http://#{worker.instance.public_ip_address}", :target => "_blank"
    else
      nil
    end
  end

  def worker_public_dns(worker)
    if worker.instance.public_dns_name
      link_to worker.instance.public_dns_name, "http://#{worker.instance.public_dns_name}", :target => "_blank"
    else
      nil
    end
  end

  def worker_sidekiq_url(worker)
    if worker.instance.public_ip_address
      link_to "(here)", "http://#{(worker.instance.public_ip_address + sidekiq_web_path)}", :target => "_blank"
    else
      nil
    end
  end

end

project-1/my_app/app/views/manager/auto_scale.js.erb
$('#form-autoscale .spinner').hide();

project-1/my_app/app/views/manager/elb_status.html.haml
- AWS.memoize do
  - if !@elb.load_balancer.exists?
    = link_to "Launch Load Balancer", manager_start_elb_path, data: {method: :post, confirm: "Are you sure?"}, class: "btn btn-success"
    %p
      %strong You must launch a load balancer before adding Workers.
  - else
    .container-fluid
      .row
        %table.table.table-striped
          %thead
            %tr
              %th Name
              %th URL
          %tbody
            %tr
              %td= @elb.name
              %td= link_to @elb.load_balancer.dns_name, @elb.url, :target => "_blank"

project-1/my_app/app/views/manager/image_stats.html.haml
%p
  There are a total of
  %strong= Image.s3_bucket.objects.count
  objects (images, thumbnails) in the 
  %strong #{Image.s3_bucket_name}
  S3 bucket, across
  %strong= Image.count
  (database) images.
%p
  = link_to "Purge Images", manager_purge_images_path, data: {method: :post, confirm: "This will delete all original images and associated transformations. The images will be deleted in the background. Refresh the page to monitor progress. Are you sure?"}, class: "btn btn-danger"

project-1/my_app/app/views/manager/new.html.haml
= provide(:title, "Log In")

= form_tag(manager_login_path) do
  %h3.form-signin-heading Manager Log In
  
  .input-group
    = label_tag "login", nil, class: "sr-only"
    = text_field_tag "login", nil, class: "form-control", placeholder: "Login", autofocus: true
    = label_tag "password", nil, class: "sr-only"
    = text_field_tag "password", nil, class: "form-control", placeholder: "Password"
  .form-group
  .form-group
    = submit_tag "Log In", class: "btn btn-primary"

project-1/my_app/app/views/manager/reset_alarms.js.erb
alert("Alarms reset!");

project-1/my_app/app/views/manager/worker_status.html.haml
- AWS.memoize do
  - if @elb.load_balancer.exists?
    .container-fluid
      .row
        %table.table.table-striped
          %thead
            %tr
              %th Name
              %th AMI
              %th IP
              %th Hostname
              %th Status
              %th ELB Health
              %th CPU %
              %th Sidekiq
              %th Actions
          %tbody
            - @workers.each do |w|
              - AWS.memoize do
                %tr
                  %td= w.instance.id
                  %td= w.instance.image.id
                  %td= worker_public_ip(w)
                  %td= worker_public_dns(w)
                  %td= w.status
                  %td= worker_health(w)
                  %td= w.latest_cpu_utilization.to_f.round(2)
                  %td= worker_sidekiq_url(w)

                  %td
                    / - if w.safe_to_stop?
                    /   = link_to "Stop", manager_worker_stop_worker_path(w.instance.id), data: {method: :delete, confirm: "Are you sure? This will prevent any pending Sidekiq jobs from completing."}, class: "btn btn-danger"
                    /   |
                    - if w.safe_to_terminate?
                      = link_to "Terminate", manager_worker_terminate_worker_path(w.instance.id), data: {method: :delete, confirm: "Are you sure? This will PERMANENTLY delete any pending Sidekiq jobs."}, class: "btn btn-danger"

    = link_to "Launch Another Instance", manager_start_worker_path, data: {method: :put, confirm: "Are you sure?"}, class: "btn btn-info"
  - else
    No load balancer exists. Launch one to attach Workers.

project-1/my_app/app/views/manager/worker_status.js.erb
$.ajax({
    url: "/manager/worker_status",
    cache: false,
    success: function(html){
      $("#worker-status").html(html);
      $('#form-worker-refresh .spinner').hide();
    }
});